run_test error1.test